### ISSUE TITLE
How to use without docker compose ?

### ISSUE THREAD

**Issue by kgaut** [TehesFR/docker-solr#1]
Hi,

I used to use your previous docker image `tehes/solr-4.9.0` for a D7 website that need a solr engine, directly with docker, without docker-compose.

At the time I only had to throw in a CLI : 
```
docker run -d -p 127.0.0.1:2222:22 -p 127.0.0.1:8080:8080 -t -i tehes/solr-4.9.0
```
and then reindex content with drush.

It seems that port mapping has changed ? I can't connect from Drupal to solr engine.

Here's the search api options I tried : 

```
    'options' => array(
      'host' => '127.0.0.1',
      'port' => '8080',
      'path' => '/solr/drupal',
      'http_user' => '',
      'http_pass' => '',
      'excerpt' => 0,
      'retrieve_data' => 0,
      'highlight_data' => 0,
      'http_method' => 'POST',
    ),
```

Kevin

**Comment by TehesFR** [comment]
Hi @kgaut,

I'm really sorry for the late answer, but I haven't been notified for your issue...
The SOLR port inside the container is now 8983, so you need to start the container with:
```
docker run -itd -p 8080:8983 tehes/docker-solr:tag
```

**Comment by kgaut** [comment]
Thanks ! I forget about this issue, I was finally able to make it working by dig a bit within the docker compose configuration.

Thanks for your work !
